# BEGIN W3TC CDN
location ~ \.(ttf|ttc|otf|eot|woff|woff2|font.css)$ {
    etag off;
    if_modified_since exact;
    add_header Referrer-Policy "no-referrer-when-downgrade";
    add_header Access-Control-Allow-Origin "*";
}
# END W3TC CDN
# BEGIN W3TC Browser Cache
add_header Referrer-Policy "no-referrer-when-downgrade";
# END W3TC Browser Cache
